const SET_COMPANY_PASSWORD = 'SET_PASSWORD';
const SET_COMPANY_EMAIL = 'SET_EMAIL';
const SET_COMPANY_NAME = 'SET_COMPANY_NAME';
const SET_USER_TYPE = 'SET_USER_TYPE';

export default {
  SET_COMPANY_PASSWORD,
  SET_COMPANY_EMAIL,
  SET_COMPANY_NAME,
  SET_USER_TYPE,
};
