const SET_USER_TYPE = 'SET_USER_TYPE';
const LOG_IN = 'LOG_IN';
const LOG_OUT = 'LOG_OUT';
const LOGIN_PROCESS_START = 'session/LOGIN_PROCESS_START';
const LOGIN_PROCESS_SUCCEED = 'session/LOGIN_PROCESS_SUCCEED';
const LOGIN_PROCESS_FAILED = 'session/LOGIN_PROCESS_FAILED';

export default {
  SET_USER_TYPE,
  LOG_IN,
  LOG_OUT,
  LOGIN_PROCESS_START,
  LOGIN_PROCESS_SUCCEED,
  LOGIN_PROCESS_FAILED,
};
