const SET_DEVELOPER_PASSWORD = 'SET_DEVELOPER_PASSWORD';
const SET_DEVELOPER_EMAIL = 'SET_DEVELOPER_EMAIL';
const SET_DEVELOPER_NAME = 'SET_DEVELOPER_NAME';
const SET_DEVELOPER_SURNAME = 'SET_DEVELOPER_SURNAME';
const SET_DEVELOPER_STACK = 'SET_DEVELOPER_STACK';
const SET_DEVELOPER_EXPERIENCE = 'SET_DEVELOPER_EXPERIENCE';
const SET_DEVELOPER_DESCRIPTION = 'SET_DEVELOPER_DESCRIPTION';

export default {
  SET_DEVELOPER_PASSWORD,
  SET_DEVELOPER_EMAIL,
  SET_DEVELOPER_NAME,
  SET_DEVELOPER_SURNAME,
  SET_DEVELOPER_STACK,
  SET_DEVELOPER_EXPERIENCE,
  SET_DEVELOPER_DESCRIPTION,
};
